# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - agrotrack-profile-service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean package -DskipTests # Cambiado install por package (más rápido y limpio para despliegues)

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: 'target/*.jar' # Simplificado para evitar conflictos de workspace

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: . # <-- FUERZA a que el JAR se descargue exactamente en la raíz del deploy

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C616E73DD4A645908D3E044A00B3B02F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4643C258681E4CD59B530170063EAB70 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_42599E3B9B894FED810E4DB56A2FAC1B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'agrotrack-profile-service'
          slot-name: 'Production'
          package: '*.jar' # Al haber forzado la descarga en ".", buscará cualquier archivo .jar en la raíz con éxito
